# Generated by Django 3.2.18 on 2023-04-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20230406_0806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
