# Generated by Django 3.2.18 on 2023-04-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='energy',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
        ),
    ]
