# Generated by Django 3.2.18 on 2023-04-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
