# Generated by Django 3.2.18 on 2023-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_dailyenergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_cleared_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
