# Generated by Django 3.2.18 on 2023-04-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_task_last_cleared_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_cleared_date',
        ),
    ]
